#!/bin/bash
if [ "$@" ]; then
	if [ -f "$@" ]; then
		echo "Moving $@ to $HOME/.local/bin/ ..."
		mv "$@" "$HOME/.local/bin/"
		echo "Marking $HOME/.local/bin/$@ as executable ..."
		chmod +x "$HOME/.local/bin/$@"
		echo "Done!"
	else
		echo "$(basename $0): $@: No such file."
	fi
else
	echo "Please enter a filename."
fi
